server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:lanchonetebd
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop

  messages:
    basename: messages/validation

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs